### ISSUE TITLE
Support Rubocop 0.50.0

### ISSUE THREAD

**Issue by anthony-robin** [carolineartz/rubocop-rails-order_model_macros#2]
Hi !
I tried to install your gem on my Rails project which has `Rubocop` version to `0.50.0`.
I couldn't make it to work as your gem doesn't have support for versions upper than `0.47`.

May you create a new release supporting `0.50` ?
Thanks :)

**Comment by carolineartz** [comment]
Sure I can try to do that sometime this week or next. Thanks for the heads up.

**Comment by anthony-robin** [comment]
any news on this ? :)

**Comment by carolineartz** [comment]
@anthony-robin it looks like the signature of `Rubocop::Cop::Cop#add_offense` changed to no longer support positional args as of [0.52](https://github.com/bbatsov/rubocop/commit/a1893ba57b43d793c15bd66f6db47950ae2ef7bc). Any chance you can ~> 0.52.0?

**Comment by anthony-robin** [comment]
Do you mean your code won't work with `0.52` or do you plan to change it to be compatible ?

**Comment by carolineartz** [comment]
I mean it wouldn't work with 0.50.0, but it would work with 0.52 (actually >= 0.51).

**Comment by anthony-robin** [comment]
Yes, that's perfect :)

**Comment by carolineartz** [comment]
ok, i just pushed 0.2.0 to rubygems, good to close this issue?

**Comment by anthony-robin** [comment]
Thanks !
