### ISSUE TITLE
Make this gem compatible with latest `Rubocop` version 1.18.4

### ISSUE THREAD

**Issue by yedhink** [carolineartz/rubocop-rails-order_model_macros#3]
Thanks for taking the effort to create this gem.

Seems like a very useful gem and should be part of the rubocop-rails gem itself in my opinion.

Currently, I'm not able to add this gem to my Rails project.

It shows the following error:
```
Bundler could not find compatible versions for gem "rubocop":
  In snapshot (Gemfile.lock):
    rubocop (= 1.18.4)

  In Gemfile:
    rubocop (~> 1.18.4)

    rubocop-rails-order_model_macros was resolved to 0.1.24, which depends on
      rubocop (~> 0.47.1)
```

I think this gem might be using some old Rubocop cop rules.

Let me know if it's feasible to update this gem.

**Comment by carolineartz** [comment]
@yedhink whelp, I haven't checked this in years obviously, sorry about that! Is this still something you are interested in and/or you're not aware of anything else in the community that covers this at this point? if not, I could probably update it!

**Comment by yedhink** [comment]
@carolineartz I think https://github.com/rubocop/rubocop/blob/master/lib/rubocop/cop/layout/class_structure.rb takes care of this job.

Closing this issue.
